# Generated by Django 3.0.3 on 2020-02-26 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='Combat started')),
                ('ended', models.DateTimeField(verbose_name='Combat ended')),
                ('encounter', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static', models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй')], verbose_name=1)),
                ('raid_day', models.DateField(null=True)),
                ('flushed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('ep', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Combat')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Player')),
            ],
        ),
        migrations.AddField(
            model_name='combat',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Report'),
        ),
    ]
