# Generated by Django 2.2.10 on 2020-02-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0002_itemconsumption_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='raid_name',
            field=models.CharField(default='Raid Name', max_length=200),
            preserve_default=False,
        ),
    ]
