# Generated by Django 2.2.10 on 2020-03-01 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0003_report_raid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='encounter',
            field=models.CharField(max_length=200, verbose_name='Бой'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='ended',
            field=models.DateTimeField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Report', verbose_name='Отчет'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='started',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='combat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Combat', verbose_name='Бой'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='ep',
            field=models.IntegerField(verbose_name='EP'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='used_at',
            field=models.DateTimeField(verbose_name='Применено'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='report',
            name='flushed',
            field=models.BooleanField(default=False, verbose_name='Очки начислены'),
        ),
        migrations.AlterField(
            model_name='report',
            name='raid_day',
            field=models.DateField(null=True, verbose_name='День рейда'),
        ),
        migrations.AlterField(
            model_name='report',
            name='raid_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Рейд'),
        ),
        migrations.AlterField(
            model_name='report',
            name='static',
            field=models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (2, 'Третий')], default=1, verbose_name='Статик'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
    ]
