# Generated by Django 2.2.10 on 2020-03-01 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0004_auto_20200301_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combat',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='itemconsumption',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
