# Generated by Django 2.2.10 on 2020-03-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0005_auto_20200301_2058'),
    ]

    operations = [
        migrations.RenameModel('Player', 'Character'),
        migrations.RenameField('ItemConsumption', 'player', 'character'),
    ]