# Generated by Django 2.2.10 on 2020-06-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0005_auto_20200301_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=6, verbose_name='Цвет (hex RGB)')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('spell_id', models.IntegerField(unique=True, verbose_name='ID заклинания')),
                ('item_id', models.IntegerField(unique=True, verbose_name='ID предмета')),
                ('points_for_usage', models.BooleanField(default=False, verbose_name='Давать очки за применение (без учета времени)')),
                ('points', models.IntegerField(verbose_name='Очки')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=30, verbose_name='Имя группы')),
                ('points', models.IntegerField(verbose_name='Очки')),
                ('consumables', models.ManyToManyField(to='extra_ep.Consumable')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='static',
            field=models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий')], default=1, verbose_name='Статик'),
        ),
        migrations.CreateModel(
            name='RaidRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('raid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra_ep.Raid')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Report')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Consumable')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Player')),
                ('raid_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.RaidRun')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('encounter_id', models.IntegerField(unique=True, verbose_name='ID боя. Гуглите encounter id')),
                ('raid_end', models.BooleanField(default=False, verbose_name='Конец рейда')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Raid')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra_ep.Class'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra_ep.Role'),
        ),
        migrations.CreateModel(
            name='ConsumablesSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('consumables', models.ManyToManyField(to='extra_ep.Consumable')),
                ('groups', models.ManyToManyField(to='extra_ep.ConsumableGroup')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Class')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.Role')),
            ],
            options={
                'unique_together': {('role', 'klass')},
            },
        ),
    ]
