# Generated by Django 2.2.10 on 2020-06-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0006_auto_20200627_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raidrun',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='raidrun',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
