# Generated by Django 2.2.10 on 2020-04-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0001_initial'),
        ('extra_ep', '0007_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Персонаж'),
        ),
        migrations.CreateModel(
            name='RaidTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_base_template', models.BooleanField(default=False)),
                ('max_tanks', models.IntegerField(verbose_name='Максисум танков')),
                ('max_healers', models.IntegerField(verbose_name='Максисум хилов')),
                ('max_damage_dealers', models.IntegerField(verbose_name='Максисум ДД')),
                ('max_total', models.IntegerField(verbose_name='Максисум игроков в рейде')),
                ('damage_dealers', models.ManyToManyField(related_name='_raidtemplate_damage_dealers_+', to='extra_ep.Character', verbose_name='ДД')),
                ('healers', models.ManyToManyField(related_name='_raidtemplate_healers_+', to='extra_ep.Character', verbose_name='Хилы')),
                ('raid_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='extra_ep.Character', verbose_name='РЛ')),
                ('tanks', models.ManyToManyField(related_name='_raidtemplate_tanks_+', to='extra_ep.Character', verbose_name='Танки')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaidEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('raid', models.CharField(choices=[('mc', 'Огненные Недра'), ('bwl', 'Логово Крыла Тьмы'), ('zg', 'ЗулГурруб')], max_length=10, verbose_name='Рейд')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra_ep.RaidTemplate')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
