# Generated by Django 2.2.10 on 2020-06-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0007_auto_20200627_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
