# Generated by Django 2.2.10 on 2020-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0008_consumable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidrun',
            name='minimum_uptime',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='raidrun',
            name='points_coefficient',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='raidrun',
            name='required_uptime',
            field=models.FloatField(default=0.85),
        ),
    ]
