# Generated by Django 2.2.10 on 2020-08-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0011_auto_20200808_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumable',
            old_name='points',
            new_name='points_for_usage',
        ),
    ]
