# Generated by Django 2.2.10 on 2020-08-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0012_auto_20200808_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='points_over_raid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очки за рейд'),
        ),
        migrations.AddField(
            model_name='raid',
            name='default_minimum_uptime',
            field=models.FloatField(default=0.5, verbose_name='Минимальный аптайм по умолчанию'),
        ),
        migrations.AddField(
            model_name='raid',
            name='default_points_coefficient',
            field=models.FloatField(default=1, verbose_name='Коэффициент очков по времени по умолчанию'),
        ),
        migrations.AddField(
            model_name='raid',
            name='default_required_uptime',
            field=models.FloatField(default=0.85, verbose_name='Необходимый аптайм по умолчанию'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_hard_mode',
            field=models.BooleanField(default=False, verbose_name='Режим освоения, очки за использование'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='points_for_usage',
            field=models.IntegerField(verbose_name='Очки за одно использование'),
        ),
        migrations.AlterField(
            model_name='raidrun',
            name='minimum_uptime',
            field=models.FloatField(default=0.5, verbose_name='Минимальный аптайм'),
        ),
        migrations.AlterField(
            model_name='raidrun',
            name='points_coefficient',
            field=models.FloatField(default=1, verbose_name='Коэффициент очков по времени'),
        ),
        migrations.AlterField(
            model_name='raidrun',
            name='required_uptime',
            field=models.FloatField(default=0.85, verbose_name='Необходимый аптайм'),
        ),
    ]
