# Generated by Django 2.2.10 on 2020-08-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0014_auto_20200808_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID предмета'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='spell_id',
            field=models.IntegerField(verbose_name='ID заклинания'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='usage_based_item',
            field=models.BooleanField(default=False, verbose_name='Давать очки за использование, а не за время'),
        ),
        migrations.AlterField(
            model_name='report',
            name='static',
            field=models.IntegerField(choices=[(2, 'Второй'), (3, 'Третий'), (1, 'Первый :(')], default=2, verbose_name='Статик'),
        ),
    ]
