# Generated by Django 3.1 on 2020-08-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0016_auto_20200826_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidrun',
            name='active',
        ),
        migrations.AlterField(
            model_name='boss',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='consumableusage',
            name='begin',
            field=models.DateTimeField(verbose_name='Начало действия'),
        ),
        migrations.AlterField(
            model_name='consumableusage',
            name='end',
            field=models.DateTimeField(verbose_name='Окончание действия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='raidrun',
            name='begin',
            field=models.DateTimeField(null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='raidrun',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
