# Generated by Django 3.1 on 2020-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0017_auto_20200826_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='is_world_buff',
            field=models.BooleanField(blank=True, default=False, verbose_name='Мировой баф'),
        ),
    ]
