# Generated by Django 3.1 on 2020-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0018_consumable_is_world_buff'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidrun',
            name='players',
            field=models.ManyToManyField(to='extra_ep.Player', verbose_name='Игроки'),
        ),
    ]
