# Generated by Django 3.1 on 2020-08-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0019_raidrun_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablegroup',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
    ]
