# Generated by Django 3.1 on 2020-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0020_consumablegroup_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_hard_mode',
        ),
        migrations.AddField(
            model_name='raid',
            name='default_is_hard_mode',
            field=models.BooleanField(default=False, verbose_name='Режим освоения, очки за использование'),
        ),
        migrations.AddField(
            model_name='raidrun',
            name='is_hard_mode',
            field=models.BooleanField(default=False, verbose_name='Режим освоения, очки за использование'),
        ),
    ]
