# Generated by Django 3.1 on 2020-09-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0022_remove_consumablegroup_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='limit_over_report',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лимит в отчете (самое то для титанок)'),
        ),
        migrations.AlterField(
            model_name='consumableusagelimit',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='extra_ep.consumable', verbose_name='Расходник'),
        ),
    ]
