# Generated by Django 3.1 on 2020-09-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0023_auto_20200910_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='check_by_aura_apply',
            field=models.BooleanField(default=False, verbose_name='Проверять по ауре'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность, в минутах'),
        ),
    ]
