# Generated by Django 3.1 on 2021-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_ep', '0025_consumable_broken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconsumption',
            name='combat',
        ),
        migrations.RemoveField(
            model_name='itemconsumption',
            name='player',
        ),
        migrations.AlterField(
            model_name='report',
            name='static',
            field=models.IntegerField(choices=[(2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (1, 'Первый :(')], default=2, verbose_name='Статик'),
        ),
        migrations.DeleteModel(
            name='Combat',
        ),
        migrations.DeleteModel(
            name='ItemConsumption',
        ),
    ]
